# qDrop configuration
#     Have fun!
blocks-dig-prevent-message: '&cThere is no drop from this block!'
blocks-dig-prevent:
  - IRON_ORE
  - DIAMOND_ORE
  - COAL_ORE
  - LAPIS_ORE
  - GOLD_ORE
  - EMERALD_ORE
  - REDSTONE_ORE
blocks-level-points:
  - 'STONE:1'
  - 'DIRT:1'
  - 'GRAVEL:1'
  - 'COBBLESTONE:2'
  - 'GRASS:3'
  - 'OBSIDIAN:5'
turbo-chance-increase: 10.0
turbo-bar-color: 'GREEN'
turbo-bar-message: '&2&lTurboDrop: &2{WHO}'
turbo-enabled:
  - '&8&l&m-----------------------------------'
  - '&7   TurboDrop from &2{WHO}'
  - '&7     Time remaining: &2{TIME}'
  - '&7     Additional: &2{CHANCE}%'
  - '&8&l&m-----------------------------------'
turbo-disabled:
  - '&8&l&m-----------------------------------'
  - '&7   TurboDrop is disabled.'
  - '&7     Buy: &2http://yourstore.com'
  - '&7     Additional: &2{CHANCE}%'
  - '&8&l&m-----------------------------------'
# Example: currentLevel * thisMultipiler
# So if currentLevel = 5, and thisMultipiler = 45.5
# 6 level will be on: 227(.5, but we're rounding to int)
points-upgrade-multipiler: 70.5
# Broadcasting level upgrades on chat
levels-broadcast:
  - '5'
  - '10'
  - '25'
  - '50'
  - '75'
  - '100'
  - '150'
  - '200'
  - '300'
  - '500'
  - '750'
  - '1000'
  - '2000'
  - '5000'
  - '7500'
  - '10000'
levels-broadcast-message: '&7Player &c{PLAYER} &7has now level &c{LEVEL}&7!'
gui:
  drop:
    title: '&7Drop list'
    item-color: '&2'
    lores:
      - '&8* &lvlcolorRequired level: &lvlcolor{REQUIREDLEVEL}'
      - '&8* &7Item: &2{ITEM}'
      - '&8* &7Chance: &2{CHANCE}%'
      - '&8* &7Amount: &2{AMOUNT-START}-{AMOUNT-END}'
      - '&8* &7Heights: &2{HEIGHTS-START}-{HEIGHTS-END}'
      - '&8* &7Exp: &2{EXP}'
      - '&8* &7Block: &2{BLOCK}'
      - '&8* &7Biomes: &2{BIOMES}'
      - '&8* &7Tools: &2{TOOLS}'
      - '&8* &7Level points: &2{LEVELPOINTS}'
      - ''
      - '&8* &activecolorActive: &activecolor{ACTIVE}'
cobblestone-active: '&8* &activecolorActive: &activecolor{ACTIVE}'
empty: 'Empty'
more: ' and more...'
yes: 'yes'
no: 'no'
only-player: 'That command is not available for you.'
no-permission: '&cYou dont have permission to use this command.'
level-contents: '&7Your current level is &c{LEVEL} &7(&c{LEVELPOINTS} level points&7, &c{DROPMULTI} drop multipiler&7) and you will rankup on &c{RANKUP} level points&7!'
sqlite: true
mysql:
  port: 3306
  host: localhost
  pass: ''
  user: root
  name: qDrop