# qDrop configuration
#     Have fun!
blocks-dig-prevent-message: '&cThere is no drop from this block!'
blocks-dig-prevent:
  - IRON_ORE
  - DIAMOND_ORE
  - COAL_ORE
  - LAPIS_ORE
  - GOLD_ORE
  - EMERALD_ORE
  - REDSTONE_ORE
blocks-level-points:
  - 'STONE:1'
  - 'DIRT:1'
  - 'GRAVEL:1'
  - 'COBBLESTONE:2'
  - 'GRASS:3'
  - 'OBSIDIAN:5'
# Example: currentLevel * thisMultipiler
# So if currentLevel = 5, and thisMultipiler = 45.5
# 6 level will be on: 227(.5, but we're rounding to int)
points-upgrade-multipiler: 70.5
# Broadcasting level upgrades on chat
levels-broadcast:
  - '5'
  - '10'
  - '25'
  - '50'
  - '75'
  - '100'
  - '150'
  - '200'
  - '300'
  - '500'
  - '750'
  - '1000'
  - '2000'
  - '5000'
  - '7500'
  - '10000'
levels-broadcast-message: '&7Player &c{PLAYER} &7has now level &c{LEVEL}&7!'
sqlite: true
mysql:
  port: 3306
  host: localhost
  pass: ''
  user: root
  name: qDrop